import express from "express";import helmet from "helmet";import crypto from "node:crypto";import fs from "node:fs";import path from "node:path";import Database from "better-sqlite3";import {Client} from "ssh2";import {z} from "zod";
const C=z.object({PORT:z.coerce.number().default(8787),GATEWAY_API_KEY:z.string().min(16),DATABASE_PATH:z.string().default("./data/gateway.db"),MASTER_ENCRYPTION_KEY:z.string(),WORKSPACE_AGENT_TRIGGER_ID:z.string().optional(),WORKSPACE_AGENT_ACCESS_TOKEN:z.string().optional(),SSH_CONNECT_TIMEOUT_MS:z.coerce.number().default(15000),SSH_COMMAND_TIMEOUT_MS:z.coerce.number().default(120000)}).parse(process.env);
const key=Buffer.from(C.MASTER_ENCRYPTION_KEY,"base64");if(key.length!==32)throw new Error("MASTER_ENCRYPTION_KEY must decode to 32 bytes");
const enc=(v:string)=>{const iv=crypto.randomBytes(12),c=crypto.createCipheriv("aes-256-gcm",key,iv),b=Buffer.concat([c.update(v,"utf8"),c.final()]);return[iv,c.getAuthTag(),b].map(x=>x.toString("base64url")).join(".")};const dec=(v:string)=>{const[i,t,b]=v.split(".").map(x=>Buffer.from(x,"base64url")),d=crypto.createDecipheriv("aes-256-gcm",key,i);d.setAuthTag(t);return Buffer.concat([d.update(b),d.final()]).toString("utf8")};
fs.mkdirSync(path.dirname(C.DATABASE_PATH),{recursive:true});const db=new Database(C.DATABASE_PATH);db.pragma("journal_mode=WAL");db.exec(`CREATE TABLE IF NOT EXISTS targets(id TEXT PRIMARY KEY,name TEXT,host TEXT,port INTEGER,username TEXT,private_key_enc TEXT,host_fingerprint TEXT,created_at TEXT);CREATE TABLE IF NOT EXISTS tasks(id TEXT PRIMARY KEY,prompt TEXT,target_id TEXT,status TEXT,conversation_key TEXT,result TEXT,error TEXT,conversation_url TEXT,agent_run_id TEXT,created_at TEXT,updated_at TEXT);CREATE TABLE IF NOT EXISTS events(id INTEGER PRIMARY KEY AUTOINCREMENT,task_id TEXT,type TEXT,payload TEXT,created_at TEXT);`);
const emit=(id:string,type:string,p:any)=>db.prepare("INSERT INTO events(task_id,type,payload,created_at) VALUES(?,?,?,?)").run(id,type,JSON.stringify(p),new Date().toISOString());
const blocked=[/\brm\s+-rf\s+\//i,/\bmkfs\b/i,/\bshutdown\b/i,/\breboot\b/i,/\bpoweroff\b/i,/\bufw\s+(disable|reset)\b/i,/\/etc\/ssh\/sshd_config/i,/\bpasswd\s+root\b/i,/\bdd\s+if=.*\sof=\/dev\//i];
function runSSH(target:any,command:string){if(blocked.some(r=>r.test(command)))throw new Error("Command blocked by safety policy");return new Promise<any>((resolve,reject)=>{const c=new Client(),timer=setTimeout(()=>{c.end();reject(new Error("SSH command timeout"))},C.SSH_COMMAND_TIMEOUT_MS);let out="",err="";c.on("ready",()=>c.exec(command,(e,s)=>{if(e){clearTimeout(timer);c.end();return reject(e)}s.on("data",d=>out+=d).stderr.on("data",d=>err+=d);s.on("close",code=>{clearTimeout(timer);c.end();resolve({code,stdout:out.slice(-100000),stderr:err.slice(-100000)})})})).on("error",e=>{clearTimeout(timer);reject(e)}).connect({host:target.host,port:target.port,username:target.username,privateKey:dec(target.private_key_enc),readyTimeout:C.SSH_CONNECT_TIMEOUT_MS,hostVerifier:target.host_fingerprint?hash=>hash===target.host_fingerprint:undefined});});}
async function trigger(id:string,prompt:string,targetId?:string){if(!C.WORKSPACE_AGENT_TRIGGER_ID||!C.WORKSPACE_AGENT_ACCESS_TOKEN)return;const input=`XDIGITEX TASK_ID=${id}\nTARGET_ID=${targetId??"none"}\n${prompt}\nUse Xdigitex MCP tools. Finish by calling complete_task.`;const r=await fetch(`https://api.chatgpt.com/v1/workspace_agents/${C.WORKSPACE_AGENT_TRIGGER_ID}/trigger`,{method:"POST",headers:{authorization:`Bearer ${C.WORKSPACE_AGENT_ACCESS_TOKEN}`,"content-type":"application/json","idempotency-key":id,"openai-beta":"workspace_agent_runs=v1"},body:JSON.stringify({conversation_key:`xdigitex-${targetId??id}`,input})});const b:any=await r.json();if(!r.ok)throw new Error(JSON.stringify(b));db.prepare("UPDATE tasks SET conversation_url=?,agent_run_id=?,updated_at=? WHERE id=?").run(b.conversation_url,b.agent_trigger_run_id,new Date().toISOString(),id)}
const app=express();app.use(helmet());app.use(express.json({limit:"2mb"}));app.get("/health",(_,r)=>r.json({ok:true,service:"xdigitex-chatgpt-gateway"}));app.use((q,r,n)=>{if(q.path==="/health")return n();if(q.headers.authorization!==`Bearer ${C.GATEWAY_API_KEY}`)return r.status(401).json({error:"unauthorized"});n()});
app.post("/v1/targets",(q,r)=>{const s=z.object({name:z.string(),host:z.string(),port:z.number().default(22),username:z.string(),privateKey:z.string(),hostFingerprint:z.string().optional()}).parse(q.body),id=crypto.randomUUID();db.prepare("INSERT INTO targets VALUES(?,?,?,?,?,?,?,?)").run(id,s.name,s.host,s.port,s.username,enc(s.privateKey),s.hostFingerprint??null,new Date().toISOString());r.status(201).json({id,name:s.name,host:s.host,port:s.port,username:s.username})});
app.post("/v1/tasks",async(q,r)=>{const s=z.object({prompt:z.string().min(1),targetId:z.string().optional()}).parse(q.body),id=crypto.randomUUID(),now=new Date().toISOString();db.prepare("INSERT INTO tasks VALUES(?,?,?,?,?,?,?,?,?,?,?)").run(id,s.prompt,s.targetId??null,"queued",null,null,null,null,null,now,now);emit(id,"queued",{});trigger(id,s.prompt,s.targetId).catch(e=>{db.prepare("UPDATE tasks SET status='failed',error=?,updated_at=? WHERE id=?").run(String(e),new Date().toISOString(),id);emit(id,"trigger_failed",{error:String(e)})});r.status(202).json({id,status:"queued"})});
app.get("/v1/tasks/:id",(q,r)=>{const row=db.prepare("SELECT * FROM tasks WHERE id=?").get(q.params.id);row?r.json(row):r.status(404).json({error:"not found"})});
app.listen(C.PORT,()=>console.log(`Xdigitex gateway listening on :${C.PORT}`));export {app,db,runSSH,emit};